### ISSUE TITLE
Lines not working

### ISSUE THREAD

**Issue by felipeacsi** [JuliaComputing/KML.jl#11]
Hello, I've been using this package since 0.1.0 (thanks for the development!) but since 0.2.0 I can't define lines that are readable by Google Earth.

An example of an output is:

```<?xml encoding="UTF-8" version="1.0"?>
<kml xmlns="http://earth.google.com/kml/2.2">
  <Document>
    <Folder>
      <name>Barreras</name>
      <Placemark>
        <name>Barrera-LT01</name>
        <LineString>
          <coordinates>-70.78367300816775, -34.415271246424886
-70.78358070922826, -34.415403734874154</coordinates>
        </LineString>
      </Placemark>
    </Folder>
  </Document>
</kml>
```

I suppose the `coordinates` tags and lack of indentation could be causing the problem. The code for generating this is working as expected in 0.1.1 but not in 0.2.x (none of them).

Could you check, please? The code hasn't problems working but points, but there are issues with 2 or more coordinates in an element. If you need more information, tell me please.

Thanks in advance

Felipe

**Comment by joshday** [comment]
Hmm, can you try removing the spaces after the commas in the `<coordinates>` tag?

From what I'm reading, that might be the problem.
