### ISSUE TITLE
Error when encountering tags outside of the KML spec

### ISSUE THREAD

**Issue by DiracM** [JuliaComputing/KML.jl#8]
I'm having an issue with the toolbox. I'm on Julia 1.9, with the current KML.jl and I have created a Placemark (in annex) and when I try to open with the toolbox I have the following error:

> ArgumentError: invalid index: nothing of type Nothing
> Stacktrace:
>   [1] to_index(i::Nothing)
>     @ Base .\indices.jl:300
>   [2] to_index(A::Vector{UInt8}, i::Nothing)
>     @ Base .\indices.jl:277
>   [3] _to_indices1(A::Vector{UInt8}, inds::Tuple{Base.OneTo{Int64}}, I1::Nothing)
>     @ Base .\indices.jl:359
>   [4] to_indices
>     @ .\indices.jl:354 [inlined]
>   [5] to_indices
>     @ .\indices.jl:345 [inlined]
>   [6] getindex
>     @ .\abstractarray.jl:1294 [inlined]
>   [7] get_attributes(data::Vector{UInt8}, i::Int64, j::Int64)
>     @ XML C:\Users\dfsma\.julia\packages\XML\SrduN\src\raw.jl:126
>   [8] attributes(o::XML.Raw)
>     @ XML C:\Users\dfsma\.julia\packages\XML\SrduN\src\raw.jl:164
>   [9] getproperty
>     @ C:\Users\dfsma\.julia\packages\XML\SrduN\src\XML.jl:55 [inlined]
>  [10] Node(node::LazyNode)
>     @ XML C:\Users\dfsma\.julia\packages\XML\SrduN\src\XML.jl:126
>  [11] iterate(g::Base.Generator{Vector{LazyNode}, Type{Node}}, s::Int64)
>     @ Base .\generator.jl:47
>  [12] collect_to!(dest::Vector{Node}, itr::Base.Generator{Vector{LazyNode}, Type{Node}}, offs::Int64, st::Int64)
>     @ Base .\array.jl:840
>  [13] collect_to_with_first!(dest::Vector{Node}, v1::Node, itr::Base.Generator{Vector{LazyNode}, Type{Node}}, st::Int64)
>     @ Base .\array.jl:818
>  [14] _collect(c::Vector{LazyNode}, itr::Base.Generator{Vector{LazyNode}, Type{Node}}, #unused#::Base.EltypeUnknown, isz::Base.HasShape{1})
>     @ Base .\array.jl:812
>  [15] collect_similar(cont::Vector{LazyNode}, itr::Base.Generator{Vector{LazyNode}, Type{Node}})
>     @ Base .\array.jl:711
>  [16] map(f::Type, A::Vector{LazyNode})
>     @ Base .\abstractarray.jl:3261
>  [17] Node(node::LazyNode)
>     @ XML C:\Users\dfsma\.julia\packages\XML\SrduN\src\XML.jl:128
>  [18] iterate(g::Base.Generator{Vector{LazyNode}, Type{Node}}, s::Int64)
>     @ Base .\generator.jl:47
>  [19] collect_to!(dest::Vector{Node}, itr::Base.Generator{Vector{LazyNode}, Type{Node}}, offs::Int64, st::Int64)
>     @ Base .\array.jl:840
>  [20] collect_to_with_first!(dest::Vector{Node}, v1::Node, itr::Base.Generator{Vector{LazyNode}, Type{Node}}, st::Int64)
>     @ Base .\array.jl:818
>  [21] _collect(c::Vector{LazyNode}, itr::Base.Generator{Vector{LazyNode}, Type{Node}}, #unused#::Base.EltypeUnknown, isz::Base.HasShape{1})
>     @ Base .\array.jl:812
>  [22] collect_similar(cont::Vector{LazyNode}, itr::Base.Generator{Vector{LazyNode}, Type{Node}})
>     @ Base .\array.jl:711
>  [23] map(f::Type, A::Vector{LazyNode})
>     @ Base .\abstractarray.jl:3261
>  [24] Node(node::LazyNode)
>     @ XML C:\Users\dfsma\.julia\packages\XML\SrduN\src\XML.jl:128
>  [25] iterate(g::Base.Generator{Vector{LazyNode}, Type{Node}}, s::Int64)
>     @ Base .\generator.jl:47
>  [26] collect_to!(dest::Vector{Node}, itr::Base.Generator{Vector{LazyNode}, Type{Node}}, offs::Int64, st::Int64)
>     @ Base .\array.jl:840
>  [27] collect_to_with_first!(dest::Vector{Node}, v1::Node, itr::Base.Generator{Vector{LazyNode}, Type{Node}}, st::Int64)
>     @ Base .\array.jl:818
>  [28] _collect(c::Vector{LazyNode}, itr::Base.Generator{Vector{LazyNode}, Type{Node}}, #unused#::Base.EltypeUnknown, isz::Base.HasShape{1})
>     @ Base .\array.jl:812
>  [29] collect_similar(cont::Vector{LazyNode}, itr::Base.Generator{Vector{LazyNode}, Type{Node}})
>     @ Base .\array.jl:711
>  [30] map(f::Type, A::Vector{LazyNode})
>     @ Base .\abstractarray.jl:3261
>  [31] Node(node::LazyNode)
>     @ XML C:\Users\dfsma\.julia\packages\XML\SrduN\src\XML.jl:128
>  [32] iterate(::Base.Generator{Vector{LazyNode}, Type{Node}})
>     @ Base .\generator.jl:47
>  [33] _collect(c::Vector{LazyNode}, itr::Base.Generator{Vector{LazyNode}, Type{Node}}, #unused#::Base.EltypeUnknown, isz::Base.HasShape{1})
>     @ Base .\array.jl:802
>  [34] collect_similar(cont::Vector{LazyNode}, itr::Base.Generator{Vector{LazyNode}, Type{Node}})
>     @ Base .\array.jl:711
>  [35] map(f::Type, A::Vector{LazyNode})
>     @ Base .\abstractarray.jl:3261
>  [36] Node(node::LazyNode)
>     @ XML C:\Users\dfsma\.julia\packages\XML\SrduN\src\XML.jl:128
>  [37] iterate(g::Base.Generator{Vector{LazyNode}, Type{Node}}, s::Int64)
>     @ Base .\generator.jl:47
>  [38] collect_to!(dest::Vector{Node}, itr::Base.Generator{Vector{LazyNode}, Type{Node}}, offs::Int64, st::Int64)
>     @ Base .\array.jl:840
>  [39] collect_to_with_first!(dest::Vector{Node}, v1::Node, itr::Base.Generator{Vector{LazyNode}, Type{Node}}, st::Int64)
>     @ Base .\array.jl:818
>  [40] _collect(c::Vector{LazyNode}, itr::Base.Generator{Vector{LazyNode}, Type{Node}}, #unused#::Base.EltypeUnknown, isz::Base.HasShape{1})
>     @ Base .\array.jl:812
>  [41] collect_similar(cont::Vector{LazyNode}, itr::Base.Generator{Vector{LazyNode}, Type{Node}})
>     @ Base .\array.jl:711
>  [42] map(f::Type, A::Vector{LazyNode})
>     @ Base .\abstractarray.jl:3261
>  [43] Node(node::LazyNode)
>     @ XML C:\Users\dfsma\.julia\packages\XML\SrduN\src\XML.jl:128
>  [44] Node
>     @ C:\Users\dfsma\.julia\packages\XML\SrduN\src\XML.jl:121 [inlined]
>  [45] read(filename::String, #unused#::Type{Node})
>     @ XML C:\Users\dfsma\.julia\packages\XML\SrduN\src\XML.jl:132
>  [46] top-level scope
>     @ REPL[75]:1

 
[parisge.zip](https://github.com/JuliaComputing/KML.jl/files/11665774/parisge.zip)

**Comment by joshday** [comment]
I discovered your initial error was actually in XML.jl, but I there were some unreleased changes that fixed it.  

I have:

1) Released a new version of XML.jl
2) Bumped KML's lower bound on XML.
3) Changed errors to warnings in KML.jl when encountering something that's not in the KML spec.

```Julia
julia> read(file, KML.KMLFile)
┌ Warning: Unhandled case encountered while trying to add child with tag `gx_CascadingStyle` to parent `Document: [Node Element <Document> (1 child)]`.
└ @ KML ~/.julia/dev/KML/src/parsing.jl:69
┌ Warning: Unhandled case encountered while trying to add child with tag `gx_CascadingStyle` to parent `Document: [Node Element <Document> (1 child)]`.
└ @ KML ~/.julia/dev/KML/src/parsing.jl:69
┌ Warning: Unhandled case encountered while trying to add child with tag `gx_fovy` to parent `LookAt: [Node Element <LookAt> (5 children)]`.
└ @ KML ~/.julia/dev/KML/src/parsing.jl:69
KMLFile (1.186 KiB)
```

I'll get a KML release out soon with the changes.

**Comment by DiracM** [comment]
Hi Joshday, just tested the new release and it's looking good. I like the approach on the code, nice job.
